name: scansafeafrica_boards
description: ScanSafeAfrica - Central Board - SUSPECT System with Auto Location, Alert, Map, Report for SAPS & CIPC
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  geolocator: ^11.0.0
  flutter_map: ^7.0.1
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
