// File generated by FlutterFire CLI - QINISO FINAL
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError('DefaultFirebaseOptions have not been configured for linux');
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyA_Your_Real_Web_Key_From_Console",
    authDomain: "scansafeafrica-boards.firebaseapp.com",
    projectId: "scansafeafrica-boards",
    storageBucket: "scansafeafrica-boards.firebasestorage.app",
    messagingSenderId: "130832397347",
    appId: "1:130832397347:web:1f0b7b98d56510e60f909d",
    measurementId: "G-9LF28329PL",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyA_Your_Real_Android_Key",
    appId: "1:130832397347:android:YOUR_ANDROID_ID",
    messagingSenderId: "130832397347",
    projectId: "scansafeafrica-boards",
    storageBucket: "scansafeafrica-boards.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyA_Your_Real_iOS_Key",
    appId: "1:130832397347:ios:YOUR_IOS_ID",
    messagingSenderId: "130832397347",
    projectId: "scansafeafrica-boards",
    storageBucket: "scansafeafrica-boards.firebasestorage.app",
    iosBundleId: "com.example.scansafeafricaBoards",
  );
}
